[package]
name = "sk_patch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
rand = "0.8.5"
regex = "1.7.3"
log = "0.4.17"
simple_logger = "4.1.0"